### PR TITLE
feat: update for Django 4.2 compatibility (#10)

### PR DESCRIPTION
**Pull request by mikkonie**
This PR bumps compatibility of the package to Django 4.2 while maintaining backwards compatibility to (at least) 3.0.

Tested with the SODAR Core Django 4.2 WIP branch.

This should probably be released as 0.5.0, I haven't yet looked into how the release process works for this repo :)

### CODE REVIEW

**Comment by holtgrewe** [comment]
LGTM, but do we really need `re_path` and not just `path`?

**Review by holtgrewe — APPROVED** [review]

**Comment by mikkonie** [comment]
> LGTM, but do we really need `re_path` and not just `path`?

[According to the official Django documentation](https://docs.djangoproject.com/en/5.0/releases/3.1/#id2), `django.conf.urls.url` was an alias for `django.urls.re_path`. specifically.

**Comment by holtgrewe** [comment]
> > LGTM, but do we really need `re_path` and not just `path`?
> 
> [According to the official Django documentation](https://docs.djangoproject.com/en/5.0/releases/3.1/#id2), `django.conf.urls.url` was an alias for `django.urls.re_path` specifically.

I see. But won't `path()` suffice?

**Comment by mikkonie** [comment]
> > > LGTM, but do we really need `re_path` and not just `path`?
> > 
> > 
> > [According to the official Django documentation](https://docs.djangoproject.com/en/5.0/releases/3.1/#id2), `django.conf.urls.url` was an alias for `django.urls.re_path` specifically.
> 
> I see. But won't `path()` suffice?

`path()` is a different method with different args. I see no point in refactoring the URL scheme for a compatibility update.

**Comment by holtgrewe** [comment]
fair enough

**Pull request merged**
